[package]
name = "rust-client"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.18.26"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.75"
w3b2-solana-program = { path = "../../w3b2-solana-program", features = ["cpi"] }
