services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.rust.builder
      args:
        SOLANA_VERSION: ${SOLANA_VERSION}
        ANCHOR_VERSION: ${ANCHOR_VERSION}
        PROGRAM_KEYPAIR_PATH: ${PROGRAM_KEYPAIR_PATH:-/keys/program-keypair.json}
    image: w3b2-builder
    pull_policy: never
    env_file:
      - .env
    profiles: ["builder", "deploy", "full"]
    volumes:
      - ./artifacts:/project/artifacts
      - ./target:/project/target
      - ./keys:/keys
    working_dir: /project
    command: >
      bash -c "
        HOST_UID=${UID:-1000} HOST_GID=${GID:-1000} /usr/local/bin/build_and_deploy.sh --build-only
      "

  solana-validator:
    build:
      context: .
      dockerfile: Dockerfile.validator
      args:
        SOLANA_VERSION: ${SOLANA_VERSION}
    env_file:
      - .env
    profiles: ["validator", "deploy", "full"]
    ports:
      - "${SOLANA_VALIDATOR_RPC_PORT:-8899}:8899"
      - "${SOLANA_VALIDATOR_WS_PORT:-8900}:8900"
      - "8901:8901"
    volumes:
      - solana-ledger:/ledger
    command: >
      bash -c "solana-test-validator --ledger /ledger --reset 2>&1 | awk '{if (!p) print; fflush()} /Processed Slot/ {p=1}'"

  deployer:
    build:
      context: .
      dockerfile: Dockerfile.rust.builder
      args:
        SOLANA_VERSION: ${SOLANA_VERSION}
        ANCHOR_VERSION: ${ANCHOR_VERSION}
        PROGRAM_KEYPAIR_PATH: ${PROGRAM_KEYPAIR_PATH:-/keys/program-keypair.json}
    image: w3b2-builder
    pull_policy: never
    profiles: ["deploy", "full"]
    depends_on:
      solana-validator:
        condition: service_started
      builder:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      - SOLANA_RPC_URL=http://solana-validator:8899
    volumes:
      - ./artifacts:/project/artifacts
      - ./keys:/keys
    working_dir: /project
    command: /usr/local/bin/build_and_deploy.sh --deploy

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.rust.builder
      args:
        SOLANA_VERSION: ${SOLANA_VERSION}
        ANCHOR_VERSION: ${ANCHOR_VERSION}
        PROGRAM_KEYPAIR_PATH: ${PROGRAM_KEYPAIR_PATH:-/keys/program-keypair.json}
    image: w3b2-builder
    pull_policy: never
    profiles: ["gateway", "full"]
    depends_on:
      solana-validator:
        condition: service_started
      deployer:
        condition: service_completed_successfully
    ports:
      - "${GATEWAY_PORT}:50051"
    env_file:
      - .env
    volumes:
      - ./artifacts:/project/artifacts
      - ./target:/project/target
      - ./keys:/keys
      - ./config.docker.toml:/project/config.docker.toml
      - gateway-data:/data
    working_dir: /project
    command: >
      bash -c "
        if [ -z \"$${PROGRAM_ID}\" ]; then
          export PROGRAM_ID=$$(cat /project/artifacts/w3b2_solana_program.json | jq -r .metadata.address);
        fi;
        export W3B2_CONNECTOR__PROGRAM_ID=$${PROGRAM_ID};
        echo 'Starting gateway with PROGRAM_ID='$${PROGRAM_ID};
        /project/target/release/w3b2-solana-gateway run --config /project/config.docker.toml
      "

  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    profiles: ["docs", "full"]
    ports:
      - "${DOCS_PORT}:8000"
    volumes:
      - ./docs:/project/docs
      - ./docs/mkdocs.yml:/project/mkdocs.yml

  example-client:
    image: w3b2-hybrid-social-network-client
    build:
      context: .
      dockerfile: Dockerfile.example-client
    pull_policy: never
    profiles: ["full"]
    ports:
      - "8501:8501"
    depends_on:
      gateway:
        condition: service_started
    volumes:
      - ./artifacts:/project/artifacts
    environment:
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=${GATEWAY_PORT}
      - SOLANA_RPC_URL=http://solana-validator:${SOLANA_VALIDATOR_RPC_PORT:-8899}
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_CLIENT_VERIFY_SSL=false
      - PYTHONUNBUFFERED=1
    command: >
      bash -c "
        while ! nc -z gateway ${GATEWAY_PORT}; do
          echo 'Waiting for gRPC gateway to be available...';
          sleep 2;
        done;
        while [ ! -f /project/artifacts/w3b2_solana_program.json ]; do
          echo 'Waiting for program artifacts...';
          sleep 2;
        done;
        export PROGRAM_ID=$$(cat /project/artifacts/w3b2_solana_program.json | jq -r .metadata.address);
        echo 'Starting client with PROGRAM_ID='$$PROGRAM_ID;
        streamlit run app.py --server.port 8501 --server.address 0.0.0.0
      "

volumes:
  solana-ledger:
  gateway-data: