FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y jq netcat-openbsd && \
    rm -rf /var/lib/apt/lists/* 

COPY examples/hybrid-social-network-client/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY examples/hybrid-social-network-client/ /app/

ENV PYTHONPATH "${PYTHONPATH}:/app"

CMD ["streamlit", "run", "app.py"]