site_name: 'W3B2 Toolset Documentation'
theme:
  name: material
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark vs light mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.tabs.link
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - toc.integrate

nav:
  - 'Home': 'index.md'
  - 'Core Concepts': 'concepts.md'
  - 'End-to-End Tutorial': 'end-to-end-workflow.md'
  - 'Code Examples':
    - '1. Initial Setup & Wallet': 'examples/01-initial-setup.md'
    - '2. The Ed25519 Instruction': 'examples/02-constructing-the-ed25519-instruction.md'
  - 'API Reference':
    - 'Solana Program': 'reference/solana-program.md'
    - 'Gateway API': 'reference/gateway-api.md'
    - 'TypeScript Client': 'reference/ts-client.md'