# --- Docs ---
FROM python:3.9-slim

WORKDIR /project

# Copy only the requirements file to leverage Docker layer caching.
COPY ./docs/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

# The content will be mounted via docker-compose.
CMD ["mkdocs", "serve", "-a", "0.0.0.0:8000"]