site_name: 'W3B2 Toolset Documentation'
theme:
  name: material
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark vs light mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.tabs.link
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - toc.integrate

nav:
  - 'Home': 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'Architecture':
    - 'Core Concepts': 'concepts.md'
    - 'High-Level Diagram': 'architecture-diagram.md'
  - 'Components':
    - '1. On-Chain Program': 'reference/solana-program.md'
    - '2. Connector Library': 'reference/connector.md'
    - '3. gRPC Gateway': 'reference/gateway-api.md'
  - 'Tutorials':
    - 'Full Workflow Example': 'end-to-end-workflow.md'